src/Entity/User.php
<?php

namespace jjansen\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping\JoinTable;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use jjansen\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="user")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $uuid;

    /**
     * @ORM\Column(type="string", length=250)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=250)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=250, unique=true)
     * @Assert\Unique(message="Die Email ist bereits vergeben")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;
    /**
     * @var array|ArrayCollection|Team[]
     *
     * @ORM\ManyToMany(targetEntity="jjansen\Entity\Team", inversedBy="members")
     * @JoinTable(name="user_team")
     */
    private $teams;

    /**
     * @var array|ArrayCollection|Vote[]
     * @ORM\OneToMany(targetEntity="jjansen\Entity\Vote", mappedBy="owner")
     */
    private $votes;
    /**
     * @var array|ArrayCollection|Feature[]
     * @ORM\OneToMany(targetEntity="jjansen\Entity\Feature", mappedBy="admin")
     */
    private $features;

    /**
     * @var array|ArrayCollection|Invitation[]
     * @ORM\OneToMany(targetEntity="jjansen\Entity\Invitation", mappedBy="owner")
     */
    private $invitations;

    public function __construct()
    {
        $this->teams = new ArrayCollection();
        $this->votes = new ArrayCollection();
        $this->features = new ArrayCollection();
        $this->invitations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function setUuid(string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    /**
     * @return array|ArrayCollection|Team[]
     */
    public function getTeams()
    {
        return $this->teams;
    }

    /**
     * @param array|ArrayCollection|Team[] $teams
     * @return User
     */
    public function addTeam(Team $team): self
    {
        if (!$this->teams->contains($team) || $this->teams->isEmpty()) {
            $this->teams[] = $team;
        }
        return $this;
    }

    public function removeTeam(Team $team): self
    {
        $this->teams->removeElement($team);

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->uuid;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string)$this->uuid;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     * @return User
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * @param mixed $last_name
     * @return User
     */
    public function setLastName($last_name)
    {
        $this->last_name = $last_name;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;
        return $this;
    }

    /**
     * @return array|ArrayCollection|Vote[]
     */
    public function getVotes()
    {
        return $this->votes;
    }

    /**
     * @param Vote $vote
     * @return User
     */
    public function addVote(Vote $vote): User
    {
        if ($this->votes->isEmpty() || !$this->votes->contains($vote)) {
            $this->votes[] = $vote;
        }
        return $this;
    }

    /**
     * @param Vote $vote
     * @return Vote
     */
    public function removeVote(Vote $vote): self
    {
        $this->votes->removeElement($vote);
        return $this;
    }

    /**
     * @return array|ArrayCollection|Feature[]
     */
    public function getFeatures()
    {
        return $this->features;
    }

    /**
     * @param Feature $features
     * @return User
     */
    public function addFeature(Feature $feature): User
    {
        if (empty($this->features) || !$this->features->contains($feature)) {
            $this->features[] = $feature;
        }
        return $this;
    }

    /**
     * @param Feature $feature
     * @return User
     */
    public function removeFeature(Feature $feature): self
    {
        $this->features->removeElement($feature);
        return $this;
    }

    /**
     * @return array|ArrayCollection|Invitation[]
     */
    public function getInvitations()
    {
        return $this->invitations;
    }

    /**
     * @param Invitation
     * @return User
     */
    public function addInvitations(Invitation $invitation): User
    {
        if (empty($this->invitations) || !$this->invitations->contains($invitation)) {
            $this->invitations[] = $invitation;
        }
        return $this;
    }

    /**
     * @param Invitation $invitation
     * @return User
     */
    public function removeInvitation(Invitation $invitation): User
    {
        $this->invitations->removeElement($invitation);
        return $this;
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}ProjectManagment{% endblock %}</title>
    {% block stylesheets %}
        {# {{ encore_entry_link_tags('app') }} #}
        <!-- libaries -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU"
              crossorigin="anonymous">
        <link rel="stylesheet" href="{{ asset('css/main.style.css') }}">
        <!-- fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
              rel="stylesheet">
        <!-- meta -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
            crossorigin="anonymous"></script>
    <script
            src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous">
    </script>
    {% block javascripts %}

    {% endblock %}
</head>
<body>
{% block nav %}
    <nav class="pm-navbar-main navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid pm-navbar-container">
            <a class="pm-navbar-brand navbar-brand" href="{{ path('default') }}" id="logo">ProjectManagmentTWIG</a>
            <!-- switch between default text and user name -->
            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                <a class="pm-navbar-brand-text navbar-brand" href="{{ path('dashboard_home') }}">{{ app.user.uuid }}</a>
            {% else %}
                <a class="pm-navbar-brand-text navbar-brand" href="{{ path('account_login') }}">nicht angemeldet</a>
            {% endif %}

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="pm-navbar-nav navbar-nav mb-2 mb-lg-0">
                    <li class="pm-nav-item nav-item">
                        <a class="pm-nav-link nav-link active" aria-current="page" href="{{ path('default') }}">Startseite</a>
                    </li>
                    <li class="pm-nav-item nav-item dropdown">
                        <a class="pm-nav-link nav-link dropdown-toggle" href="#"
                           id="navbarDropdown"
                           role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Konto
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                                <li><a class="pm-dropdown-item dropdown-item" href="{{ path('dashboard_home') }}">Dashboard</a>
                                </li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                                <li><a class="pm-dropdown-item dropdown-item" href="{{ path('account_logout') }}">Abmelden</a>
                                </li>
                            {% else %}
                                <li><a class="pm-dropdown-item dropdown-item" href="{{ path('account_login') }}">Anmelden</a>
                                </li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}
{% block body %}{% endblock %}
</body>
</html>

templates/index.html.twig
<!doctype HTML>
<html>
<head>
    <!-- libaries -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/main.style.css') }}">
    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet">
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ProMa: Dashboard</title>

</head>
<body>
<!-- NAVBAR -->
<nav class="navbar pm-navbar-dash navbar-expand-lg navbar-light bg-light position-fixed w-100">
    <a class="navbar-brand" href="{{ path('dashboard_home') }}">ProMa Dashboard</a>
    <a role="button" class="d-block d-md-none" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
       aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ path('default') }}">Startseite</a>
            </li>
        </ul>
    </div>

</nav>
<div class="container-fluid pm-dash-container">

    <!-- Main content -->
    <div class="container-fluid pm-dash-content row p-0">
        <!-- SIDEBAR -->
        <nav class="pm-dash-sidebar col-auto d-none d-lg-block" id="pm-sidebar-1">
            <div class="pm-dash-side-background"></div>
            <div class="container pm-dash-container">
                <div class="container pm-dash-profil-container">
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        <img class="pm-sidebar-profil-icon" src="{{ asset('imgs/profil.png') }}" alt="Profilbild"
                             width="50" height="50" aria-hidden="true">
                        <div class="pm-sidebar-collapse">
                            <h1>{{ app.user.name }} {{ app.user.lastName }}</h1>
                            <span class="rounded">{{ app.user.uuid }}</span>
                        </div>
                        <img onclick="switchSidebar()" id="sidebar-switch-btn"
                             class="pm-sidebar-toggle-btn mx-auto d-block mt-1" src="{{ asset('imgs/expand.png') }}"
                             alt="Sidebar" width="18" height="18">

                    {% endif %}
                </div>
                <ul class="pm-dash-sidebar-nav">
                    <a href="{{ path('dashboard_home') }}">
                        <li class="pm-sidebar-navlink">
                            <img src="{{ asset('imgs/home.png') }}" alt="Logo" width="32" height="32"
                                 data-bs-toggle="tooltip" data-bs-placement="right" data-bs-title="Startseite">
                            <span class="pm-sidebar-collapse">Startseite</span>
                        </li>
                    </a>
                    <a href="{{ path('dashboard_teams') }}">
                        <li class="pm-sidebar-navlink">
                            <img src="{{ asset('imgs/team.png') }}" alt="Logo" width="32" height="32"
                                 data-bs-toggle="tooltip" data-bs-placement="right" data-bs-title="Meine Teams">
                            <span class="pm-sidebar-navlink-text pm-sidebar-collapse">Meine Teams</span>
                        </li>
                    </a>
                    <a href="{{ path('notify_home') }}">
                        <li class="pm-sidebar-navlink">
                            <img src="{{ asset('imgs/message.png') }}" alt="Logo" width="32" height="32"
                                 data-bs-toggle="tooltip" data-bs-placement="right" data-bs-title="Mitteilungen">
                            <span class="pm-sidebar-collapse">Mitteilungen</span>
                        </li>
                    </a>
                </ul>
            </div>
            <div class="container">
                <a href="{{ path('account_logout') }}">
                    <img class="mx-auto d-block" src="{{ asset('imgs/login.png') }}" alt="Abmelden" width="35"
                         height="35" data-toggle="tooltip" data-placement="top" title="Abmelden">
                </a>
            </div>
        </nav>
        <div class="container-fluid pm-dash-container-main col">
            {% block body %}
                {{ content|raw }}
            {% endblock %}
        </div>
    </div>
</div>
{% block alerts %}
    <!-- ALERTS -->
    {% for message in app.flashes('error') %}
        <div class="alert alert-danger pm-dash-alert" id="danger-alert">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success pm-dash-alert" id="danger-alert">
            {{ message }}
        </div>
    {% endfor %}
{% endblock %}
</body>
<footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
            crossorigin="anonymous"></script>
    <script
            src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous">
    </script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
            $('[data-bs-toggle="tooltip"]').tooltip()
        })
    </script>
    <script>
        function minifySidebar() {
            if (typeof (Storage) !== "undefined") {
                // close sidebar
                $(".pm-sidebar-navlink img").each(function () {
                    // console.log( index + ": " + $( this ).text() );
                    $(this).addClass("mx-auto d-block")
                });
                $(".pm-sidebar-collapse").each(function () {
                    // console.log( index + ": " + $( this ).text() );
                    $(this).addClass('d-none');
                });
            }
        }

        function expandSidebar() {
            // close sidebar
            if (typeof (Storage) !== "undefined") {
                $(".pm-sidebar-navlink img").each(function () {
                    // console.log( index + ": " + $( this ).text() );
                    $(this).removeClass("mx-auto d-block")
                });
                $(".pm-sidebar-collapse").each(function () {
                    // console.log( index + ": " + $( this ).text() );
                    $(this).removeClass('d-none');
                });
            }
        }

        function sidebarListener() {
            console.log(localStorage.getItem("sidebar"));
            if (localStorage.getItem("sidebar") === "closed") {
                minifySidebar();
            } else {
                expandSidebar();
            }
        }

        sidebarListener();

        function switchSidebar() {
            if (typeof (Storage) !== "undefined") {
                if (localStorage.getItem("sidebar") === "closed") {
                    expandSidebar();
                    $("#sidebar-switch-btn").attr("src", "/imgs/collapse.png");
                    localStorage.setItem("sidebar", "opened");
                } else {
                    minifySidebar();
                    $("#sidebar-switch-btn").attr("src", "/imgs/expand.png");
                    localStorage.setItem("sidebar", "closed");
                }
            }
        }

    </script>
    <script type="text/javascript">
        setTimeout(function () {

            // Closing the alert
            $('.alert').alert('close');
        }, 10000);
    </script>
    <script>
        function closeConfirmPopUp(id) {
            var element = document.getElementById('pm-confirm-popup-' + id);
            element.style.display = 'none';
        }

        function openConfirmPopUp(id) {
            var element = document.getElementById('pm-confirm-popup-' + id);
            element.style.display = 'inherit';
        }
    </script>
    {% block javascripts %}
    {% endblock %}
</footer>
</html>