src/Entity/Feature.php
<?php

namespace jjansen\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use jjansen\Repository\FeatureRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=FeatureRepository::class)
 * @ORM\Table(name="feature");
 * @UniqueEntity("name", message="Dieses Feature existiert bereits")
 */
class Feature extends AbstractBase
{

    /**
     * @var Project|null
     *
     * @ORM\ManyToOne(targetEntity="jjansen\Entity\Project", inversedBy="features")
     */
    private $project;

    /**
     * @Assert\NotBlank(message="Bitte fülle das Feld aus")
     * @Assert\Length(min=5, minMessage="Der Name ist zu kurz (min. 5)")
     * @Assert\Regex(pattern="/[\w]/", message="Sonderzeichen sind nicht erlaubt")
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @Assert\NotBlank
     * @Assert\Length(max=200, maxMessage="Die Beschreibung ist zu lang (max. 200)")
     * @Assert\Regex(pattern="/[\w\s!?.,;:#&äöüÄÖÜ]/", message="Nur Groß-, Kleinbuchstaben, Zahlen und einige Sonderzeichen erlaubt")
     * @ORM\Column(type="string", length=255, nullable="true")
     */
    private $description;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="jjansen\Entity\User", inversedBy="features")
     */
    private $admin;

    /**
     * @var array|ArrayCollection|Vote[]
     * @ORM\OneToMany(targetEntity="jjansen\Entity\Vote", mappedBy="feature", cascade={"persist", "refresh", "remove" })
     */
    private $votes;

    /**
     * @var int
     * @Assert\NotBlank
     * @ORM\Column(type="integer", nullable="false")
     */
    private int $status;

    public function __construct()
    {
        parent::__construct();
        $this->votes = new ArrayCollection();
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(Project $project): self
    {
        $this->project = $project;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return User
     */
    public function getAdmin(): User
    {
        return $this->admin;
    }

    /**
     * @param User $admin
     * @return Feature
     */
    public function setAdmin(User $admin): Feature
    {
        $this->admin = $admin;
        return $this;
    }

    /**
     * @return array|ArrayCollection|Vote[]
     */
    public function getVotes()
    {
        return $this->votes;
    }

    /**
     * @param Vote $vote
     * @return Feature
     */
    public function addVote(Vote $vote): Feature
    {
        if ($this->votes->isEmpty() || !$this->votes->contains($vote)) {
            $this->votes[] = $vote;
        }
        return $this;
    }

    /**
     * @param Vote $vote
     * @return Feature
     */
    public function removeVote(Vote $vote): self
    {
        $this->votes->removeElement($vote);
        return $this;
    }

    /**
     * @return int
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * @param int $status
     * @return Feature
     */
    public function setStatus(int $status): Feature
    {
        $this->status = $status;
        return $this;
    }

    public function getAveragePriority(): ?int
    {
        $sum = 0;
        foreach ($this->votes as $vote) {
            $sum += $vote->getPriority();
        }
        if ($sum === 0) {
            return null;
        }
        return round($sum / count($this->votes), 0);
    }

    public function getAverageTime(): ?float
    {
        $sum = 0;
        foreach ($this->votes as $vote) {
            $sum += $vote->getTime();
        }
        if ($sum === 0) {
            return null;
        }
        return round($sum / count($this->votes), 2);
    }

    public function hasVoted(User $user)
    {
        foreach ($this->getVotes() as $vote) {
            if ($vote->getOwner() === $user) {
                return true;
            }
        }
        return false;
    }

}

src/Entity/Project.php
<?php

namespace jjansen\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use jjansen\Repository\ProjectRepository;
use Doctrine\ORM\Mapping as ORM;
use jjansen\Service\BeautifyService;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 * @ORM\Table(name="project")
 * @ORM\HasLifecycleCallbacks()
 */
class Project extends AbstractBase
{

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="jjansen\Entity\User")
     * @Assert\NotBlank()
     */
    private $owner;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $quickid;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;


    /**
     * @var Team|null
     *
     * @ORM\ManyToOne(targetEntity="jjansen\Entity\Team", inversedBy="projects")
     * @Assert\NotBlank()
     */
    private $team;

    /**
     * @ORM\Column(type="boolean")
     * @Assert\PositiveOrZero()
     */
    private $visibility;

    /**
     * @var array|ArrayCollection|Feature[]
     *
     * @ORM\OneToMany(targetEntity="jjansen\Entity\Feature", mappedBy="project", cascade={"persist", "refresh", "remove" })
     */
    private $features;


    public function __construct()
    {
        parent::__construct();
        $this->features = new ArrayCollection();
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return User
     */
    public function getOwner(): User
    {
        return $this->owner;
    }

    /**
     * @param User $owner
     * @return Project
     */
    public function setOwner(User $owner): self
    {
        $this->owner = $owner;
        return $this;
    }

    public function getQuickid(): ?string
    {
        return $this->quickid;
    }

    public function setQuickid(string $quickid): self
    {
        $this->quickid = $quickid;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Team|null
     */
    public function getTeam(): ?Team
    {
        return $this->team;
    }

    /**
     * @param Team|null $team
     * @return Project
     */
    public function setTeam(?Team $team): Project
    {
        $this->team = $team;
        return $this;
    }


    public function getVisibility(): ?bool
    {
        return $this->visibility;
    }

    public function setVisibility(bool $visibility): self
    {
        $this->visibility = $visibility;

        return $this;
    }

    /**
     * @return array|ArrayCollection|Feature[]
     */
    public function getFeatures()
    {
        return $this->features;
    }

    /**
     * @param array|ArrayCollection|Feature[] $features
     * @return Project
     */
    public function addFeature(Feature $feature): self
    {
        if ($this->features->isEmpty() || !$this->features->contains($feature)) {
            $feature->setProject($this);
            $this->features[] = $feature;
        }
        $this->renewUpdate();
        return $this;
    }

    public function removeFeature(Feature $feature): self
    {

        $this->features->removeElement($feature);
        $this->renewUpdate();
        return $this;
    }

    public function isTeamMember(User $user): bool
    {
        $members = $this->getTeam()->getMembers();
        foreach ($members as $member) {
            if ($member->getId() === $user->getId()) {
                return true;
            }
        }
        return false;
    }
}

src/Controller/ProjectController.php
<?php

namespace jjansen\Controller;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManagerInterface;
use jjansen\Entity\Project;
use jjansen\Form\Type\ProjectCreateType;
use jjansen\Repository\ProjectRepository;
use jjansen\Repository\TeamRepository;
use jjansen\Security\TeamVoter;
use jjansen\Service\SecurityService;
use jjansen\Service\TeamService;
use jjansen\Service\TemplateService;
use jjansen\Service\ProjectService;
use jjansen\Service\BeautifyService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class ProjectController extends AbstractController
{

    private TemplateService $templating;
    private TeamService $tService;
    private SecurityService $sService;
    private ProjectService $pService;
    private Security $security;
    private EntityManagerInterface $entityManager;
    private ValidatorInterface $validator;
    private TeamRepository $teamRepository;
    private ProjectRepository $projectRepository;

    /**
     * @param TemplateService $templating
     */
    public function __construct(
        TemplateService $templating,
        TeamService $tService,
        SecurityService $sService,
        ProjectService $pService,
        Security $security,
        EntityManagerInterface $entityManager,
        ValidatorInterface $validator,
        TeamRepository $teamRepository,
        ProjectRepository $projectRepository
    ) {
        $this->templating = $templating;
        $this->tService = $tService;
        $this->sService = $sService;
        $this->pService = $pService;
        $this->security = $security;
        $this->entityManager = $entityManager;
        $this->validator = $validator;
        $this->teamRepository = $teamRepository;
        $this->projectRepository = $projectRepository;
    }

    /**
     * Load a project page with given Request
     *
     * @param Request $request
     * @return Response
     */
    public function loadProjectAction(Request $request): Response
    {
        $project = $this->projectRepository->findOneBy([
            'id' => $request->get('project_id')
        ]);
        if (!$project->isTeamMember($this->getUser())) {
            $this->addFlash('error', "Zugriff verweigert - Du bist kein Mitglied von diesem Projekt");
            return new RedirectResponse($this->generateUrl('dashboard_home'));
        }
        if (!$project) {
            $this->addFlash('error', "Project konnte nicht gefunden");
            return new RedirectResponse($this->generateUrl('dashboard_home'));
        }
        $content = $this->templating->render('Project/view.html.twig', [
            'request' => $request,
            'project' => $project
        ]);
        return new Response($content);
    }

    /**
     * Load a projects page with given Request
     *
     * @param Request $request
     * @return Response
     * @TODO: DOESNT WORK, NEEDS FIX
     */
    public function loadProjectsAction(Request $request): Response
    {
        $errors = [];
        $user = $this->security->getUser();
        // load all projects
        $projects_all = new ArrayCollection();
        $teams = $user->getTeams();
        foreach ($teams as $team) {
            $projects = $team->getProjects();
            $projects_all[] = $projects;
        }
        if (count($errors) > 0) {
            return new RedirectResponse($this->generateUrl('dashboard_home', ['errors' => $errors]));
        }
        $content = $this->templating->render('Project/view_all.html.twig', [
            'request' => $request,
            'projects' => $projects_all
        ]);
        return new Response($content);
    }

    /**
     * removes a project with given Request
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function removeAction(Request $request): Response
    {
        $project = $this->projectRepository->find($request->attributes->get('project_id'));
        $team = $project->getTeam();

        if ($_SERVER['REQUEST_METHOD'] == 'POST') {

            $user = $this->getUser();
            if ($project->getOwner() == $user || $project->getTeam()->getAdmin() == $user) {
                $this->entityManager->remove($project);
                $this->entityManager->flush();
                $this->addFlash('success', 'Das Projekt wurde erfolgreich entfernt.');
                return new RedirectResponse($this->generateUrl('dashboard_team', ['team_id' => $team->getId()]));
            }
            $this->addFlash('error', 'Der Zugriff wurde verweigert.');
            return new RedirectResponse($this->generateUrl('dashboard_team', ['team_id' => $team->getId()]));
        }
        $content = $this->templating->render('Project/delete.html.twig', [
            'request' => $request,
            'team' => $project->getTeam(),
            'project' => $project
        ]);
        return new Response($content);

    }

    /**
     * creates a project with given Request
     *
     * @param Request $request
     * @return Response
     */
    public function createAction(Request $request): Response
    {

        $project = new Project();

        $user = $this->security->getUser();
        // ONLY ALLOWED IF HE HAS TEAM
        if ($request->get('team_id', false)) {
            $team = $this->teamRepository->find($request->get('team_id'));
            $this->denyAccessUnlessGranted(TeamVoter::IS_TEAM_ADMIN, $team);
            $project->setTeam($team);
        }
        $project->setOwner($user);

        $form = $this->createForm(ProjectCreateType::class, $project, []);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $errors = $this->validator->validate($project);

            if (count($errors) > 0) {
                return $this->render('Project/create.html.twig', [
                    'form' => $form->createView(),
                    'errors' => $errors
                ]);
            }
            // check if quickid is given and valid, if not -> create
            $project->setQuickid($this->sService->checkInputQuickID($project->getQuickid()));
            $this->entityManager->persist($project);
            $this->entityManager->flush();


            return new RedirectResponse($this->generateUrl('dashboard_projects'));
        }
        return $this->render('Project/create.html.twig', [
            'form' => $form->createView()
        ]);
    }

    // ######################### PRIVATE FUNCTIONS ########################

    /**
     * Validation: validates a project with given Request
     *
     * @param Request $request
     * @return array
     */
    private function initProject(Request $request): array
    {
        // ## whole function for create project system
        // create new error array
        $errors = [];
        // filter variables
        $name = $this->sService->filterInput($request->get('name'));
        $visible = $this->sService->filterInput($request->get('visible'));
        $desc = $this->sService->filterInput($request->get('desc'));
        $team = $this->sService->filterInput($request->get('team'));

        // check if inputs are valid
        if ($this->sService->checkInput($name) != true) {
            $errors['name'] = "Der Projekt-Name darf keine Sonderzeichen enthalten";
        }
        $allowed = [
            '0' => 0,
            '1' => 1
        ];
        if ($this->sService->checkSelect($visible, $allowed) != true) {
            $errors['visible'] = "Bitte wähle eine Sichtbarkeit aus";
        }
        // ###### TODO add checkSelect for teams ##################
        if ($this->sService->checkInputOptional($desc) != true) {
            $errors['desc'] = "Die Beschreibung darf keine Sonderzeichen enthalten";
        }
        //check if project with name or quickid already exists
        if ($this->pService->loadProjectByName($name) != null) {
            $errors['project'] = "Das Projekt existiert bereits";
        }
        return $errors;
    }


}

templates/Project/create.html.twig
{% extends 'index.html.twig' %}
{% block body %}
    <div class="card w-75 mx-auto pm-header-content">
        <h1 class="mb-3 text-center">Schnell und ganz einfach.<br>Erstelle ein neues Projekt!</h1>
        {{ form_start(form) }}
        <div class="pm-project-group input-group mb-3 text-center w-100">
            {{ form_row(form.name) }}
            <button class="btn btn-outline-light pm-project-create-btn" type="submit" id="btn-project-label">erstellen
            </button>
        </div>

        <div class="accordion pm-accordion-project bg-transparent" id="accordionExample">
            <div class="pm-project-accordion-item bg-transparent accordion-item">
                <h2 class="pm-accordion-header accordion-header mb-2" id="projectPanel-headingCreate">
                    <button class="bg-transparent accordion-button collapsed pm-project-create-btn pm-project-options-btn"
                            type="button" data-bs-toggle="collapse" data-bs-target="#projectPanel-collapseCreate"
                            aria-expanded="false" aria-controls="projectPanel-collapseCreate">
                    </button>
                </h2>
                <!-- PROJECT CREATE OPTIONS -->
                <div id="projectPanel-collapseCreate" class="p-5  accordion-collapse collapse"
                     aria-labelledby="projectPanel-headingCreate">
                    <div class="pm-accordion-body accordion-body container">
                        <div class="card-body">
                            {{ form_rest(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {{ form_end(form) }}
    </div>

{% endblock %}

templates/Project/delete.html.twig
{% extends 'Team/view.html.twig' %}
{% block projectDeletePopUp %}
    <!-- Team Delete -->
    <div class="pm-confirm-popup-container" id="pm-confirm-popup-{{ project.quickid|slice(1,5) }}">
        <div class="pm-confirm-popup-inner-container rounded">
            <form action="{{ path('project_remove', {'project_id': project.id}) }}" method="POST">
                <h1>Möchtest du wirklich diese Eingabe ausführen?</h1>
                <p class="mb-5">Entfernung von {{ project.name }}</p>
                <div class="row justify-content-center">
                    <div class="col-auto">
                        <button type="button" class="btn btn-light btn-confirm-cancel"
                                onclick="closeConfirmPopUp({{ project.quickid|slice(1,5) }})">Abbrechen
                        </button>
                    </div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-primary btn-confirm-confirm">Ausführen</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/Project/view.html.twig
{% extends 'index.html.twig' %}
{% block body %}
    <div class="pm-team-view-header">
        <h1 class="pm-team-view-title position-relative">
            {{ project.name }}
            <div class="pm-team-view-category-container">
                <span class="pm-team-view-category">Project</span>
                <span class="pm-team-view-category" id="pm-category-orange">
                    {% if(project.visibility == 1) %} Offen {% else %} Privat {% endif %}
                </span>
            </div>
        </h1>
        <p class="mb-1">@{{ project.team.name }} - {{ project.quickid }}</p>

        <!-- DESCRIPTION COLLAPSE -->
        <button class="btn btn-light pm-team-view-btn" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseTeamViewDesc" aria-expanded="false" aria-controls="collapseTeamViewDesc">
            Beschreibung
        </button>
        <!-- STATS COLLAPSE -->
        <button class="btn btn-light pm-team-view-btn" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseTeamViewStats" aria-expanded="false" aria-controls="collapseTeamViewSetting">
            Statistiken
        </button>
        <!-- FEATURE COLLAPSE -->
        <a href="{{ path('feature_create', {'project_id': project.id}) }}" class="btn btn-light pm-team-view-btn"
           role="button">
            Feature hinzufügen
        </a>
        <div class="collapse pm-team-view-collapse" id="collapseTeamViewDesc">
            <div class="card card-body">
                <h4>Beschreibung</h4>
                {{ project.description }}
            </div>
        </div>
        <div class="collapse pm-team-view-collapse" id="collapseTeamViewStats">
            <div class="card card-body">
                <!-- Stats -->
                <div class="col-auto container pm-team-view-container rounded">
                    <h1 class="pm-view-container-title">Statistiken</h1>
                    <hr class="mt-2">
                    <div class="container pm-stats-list p-0">
                        <p>Update am: <span>{{ project.updated|date("d.m.Y") }}</span></p>
                        <hr>
                        <p>Erstelt am: <span>{{ project.creation|date("d.m.Y") }}</span></p>
                        <p>Project-Leiter: <span>{{ project.owner.uuid }}</span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <!-- Features -->
        <div class="col-auto container pm-team-view-container">
            <h1 class="pm-view-container-title">Features ({{ project.features|length }})</h1>
            <hr class="mt-2">
            {% if project.features %}
                {# {% for feature in project.features|sort((a,b) => a.averageTime <=> b.averageTime)|reverse %} #}
                {% for feature in project.features|sort((a,b) => a.averagePriority <=> b.averagePriority )|reverse %}
                    <article class="pm-project-view-feature rounded">
                        <div class="btn-group pm-project-view-feature-btn-container">
                            <button type="button" class="btn pm-project-view-feature-btn btn-light dropdown-toggle"
                                    data-bs-toggle="dropdown" aria-expanded="false"></button>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item"
                                       href="{{ path('feature_info', {'feature_id': feature.id}) }}">Info</a></li>
                                <li><a class="dropdown-item">Bearbeiten</a></li>
                                <li><a class="dropdown-item" role="button"
                                       href="{{ path('vote_add', {'feature_id': feature.id, 'project_id': project.id}) }}">Bewerten</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" role="button"
                                       href="{{ path('feature_delete', {'feature_id': feature.id}) }}">Löschen</a></li>
                            </ul>
                        </div>
                        <div class="row justify-content-center justify-content-lg-start position-relative">
                            <div class="col-auto pm-project-view-feature-rating-container">
                                <h1 class="pm-project-view-feature-title">{{ feature.name }}</h1>
                                <div class="pm-project-view-feature-rating">
                                    <p class="mb-1 mt-3">Bewertung:</p>
                                    {% if feature.hasVoted(app.user) == true and feature.votes is not empty %}
                                        <p style="cursor: pointer;" data-bs-toggle="tooltip" data-bs-placement="bottom"
                                           data-bs-html="true"
                                           title="Nutzer-Bewertung (Ø):<br><br>Zeitaufwand: {{ feature.averageTime }}h<br>Priorität: {{ feature.averagePriority }}">
                                            [ {{ feature.averageTime }} Stunden ]
                                        </p>
                                        <div class="row justify-content-center mx-auto" style="max-width: 230px;">
                                            {% for vote in feature.votes|sort((a,b) => a.time <=> b.time)|reverse %}
                                                {% if loop.index <= 5 %}
                                                    <div class="col-auto p-1">
                                                        <img class="pm-dash-voter-icon"
                                                             src="{{ asset('imgs/profil.png') }}" alt="Profibild"
                                                             width="15px" height="15px" data-bs-placement="bottom"
                                                             data-bs-toggle="tooltip" data-bs-html="true"
                                                             title="{{ vote.owner.uuid }} ({{ vote.owner.name }})<br><br> Zeitaufwand: {{ vote.time }}h <br> Priorität: {{ vote.priority }}">
                                                    </div>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        <p style="cursor: pointer;" data-bs-toggle="tooltip" data-bs-placement="bottom"
                                           data-bs-html="true"
                                           title="Nutzer-Bewertung (Ø):<br><br>Keine Bewertungen gefunden/sichtbar">
                                            [ N/A ]
                                        </p>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col pm-project-view-feature-container">
                                <h1 class="pm-project-view-feature-title">Beschreibung</h1>
                                <p>
                                    {{ feature.description }}
                                </p>
                                <h6>Dependencies</h6>
                                <p>Keine</p>
                            </div>
                        </div>
                        <span class="pm-project-view-feature-author">Ersteller: {{ feature.admin.uuid }} - {{ feature.creation|date("d.m.Y") }}</span>
                    </article><!-- end of feature -->
                {% endfor %}
            {% else %}
                <p> Keine Features zum laden.</p>
            {% endif %}
        </div>
    </div>
    {% block votePopUp %}
    {% endblock %}
    {% block deletePopUp %}
    {% endblock %}
{% endblock %}
{% block javascripts %}
    <script>

        function closeConfirmPopUp(id) {
            var element = document.getElementById('pm-confirm-popup-' + id);
            element.style.display = 'none';
        }

        function openConfirmPopUp(id) {
            var element = document.getElementById('pm-confirm-popup-' + id);
            element.style.display = 'inherit';
        }

        function openVoteContainer(id) {
            var element = document.getElementById('feature-vote-container-' + id)
            element.style.display = 'inherit';
        }

        function closeVoteContainer(id) {
            var element = document.getElementById("feature-vote-container-" + id);
            element.style.display = 'none';
        }
    </script>
{% endblock %}